#!/usr/bin/env -S helm upgrade --install tempo grafana/tempo-distributed -f
---
global:
  clusterDomain: 'cluster.local'
  dnsNamespace: 'kube-system'
  dnsService: 'coredns'
gateway:
  enabled: true
minio:
  enabled: true
storage:
  trace:
    backend: s3
    s3:
      access_key: 'grafana-tempo'
      secret_key: 'supersecret'
      bucket: 'tempo-traces'
      endpoint: 'tempo-minio:9000'
      insecure: true
traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
distributor:
  service:
    type: ClusterIP
    clusterIP: 10.233.0.4
  config:
    log_received_spans:
      enabled: true
